---
- name: determine if enterprise pve subscription exists
  stat: path=/etc/apt/apt.conf.d/86pve-nags
  register: pve_enterprise_nag_buster

- name: determine if pve community repository present
  stat: path=/etc/apt/sources.list.d/pve-community.list
  register: pve_community_repository

- name: determine if pve enterprise repository present
  stat: path=/etc/apt/sources.list.d/pve-enterprise.list
  register: pve_enterprise_repository

- name: determine if ceph repository present
  stat: path=/etc/apt/sources.list.d/ceph.list
  register: ceph_enterprise_repository

- name: determine if original no-sub ceph repository present
  lineinfile:
    regexp: enterprise$
    state: absent # try a new way of finding out whether a matching
                  # line exists in a file.  If there, this will try to
                  # remove it, and changed will be set true.  else,
                  # false
    path: /etc/apt/sources.list.d/ceph.list
  check_mode: true
  register: ceph_enterprise_line_exists
  when: ceph_enterprise_repository.stat.exists

- name: no-sub line in ceph.list?
  debug:
    msg: The "enterprise" line was not found in /etc/apt/sources.list.d/ceph.list
  when: ceph_enterprise_line_exists is defined and ceph_enterprise_line_exists.changed

- name: ensure old pve community repository removed
  command: mv /etc/apt/sources.list.d/pve-community.list /etc/apt/sources.list.d/pve-community.list.disabled
  become: true
  when: pve_community_repository.stat.exists

- name: ensure original pve enterprise repository removed
  command: mv /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-enterprise.list.disabled
  become: true
  when: pve_enterprise_repository.stat.exists

- name: ensure original ceph enterprise repository removed
  command: mv /etc/apt/sources.list.d/ceph.list /etc/apt/sources.list.d/ceph-enterprise.list.disabled
  become: true
  when: ceph_enterprise_repository.stat.exists and ceph_enterprise_line_exists is defined and ceph_enterprise_line_exists.changed

- name: ensure original ceph no-sub repository moved
  command: mv /etc/apt/sources.list.d/ceph.list /etc/apt/sources.list.d/ceph-no-subscription.list
  become: true
  when: ceph_enterprise_repository.stat.exists and ceph_enterprise_line_exists is defined and not ceph_enterprise_line_exists.changed

- name: insert our own pve no-sub file (pve-nag-buster may override it later, but we care to get the version right first)
  template:
    src: pve-no-subscription.list.j2
    dest: /etc/apt/sources.list.d/pve-no-subscription.list
  become: true

- name: insert our own ceph no-sub file (pve-nag-buster may override it later, but we care to get the version right first)
  template:
    src: ceph-no-subscription.list.j2
    dest: /etc/apt/sources.list.d/ceph-no-subscription.list
  become: true

- name: Ensures ~ansible/Downloads dir exists
  file:
    path: "/home/{{ ansible_env.USER }}/Downloads"
    state: directory

- name: copy pve-nag-buster/install.sh to pve
  copy:
    src: /home/tconnors/code/proxmox/pve-nag-buster/install.sh
    dest: "/home/{{ ansible_env.USER }}/Downloads/pve-nag-buster-install.sh"
    mode: 0755
  register: pve_nag_buster_changed

- name: install the pve nag buster
  command: /home/{{ ansible_env.USER }}/Downloads/pve-nag-buster-install.sh --offline
  become: true
  when: not pve_enterprise_nag_buster.stat.exists or pve_nag_buster_changed.changed
  register: pve_nag_installed

- name: remove prohibited packages
  apt:
    name: "{{ item }}"
    state: absent
  become: true
  with_items:
    - 'os-prober'
    - 'linux-headers-*'
    - 'linux-image-*'
    # https://github.com/ansible/ansible/issues/62262 - can't do all
    # these at once on the one invocation, because throws extraneous
    # errors when the package was never installed
  ignore_errors: true

- name: Install bootstrap requirements
  apt:
    name: ['lvm2']
    update_cache: yes
    cache_valid_time: 3600
    autoremove: no
    state: present
  become: true

- name: "search for LVM blacklist"
  register: lvm_conf_ansible_marker_exists
  check_mode: yes # cause this to become just a test.  If there's already
                  # an ANSIBLE marker, then this will think line is
                  # being replaced, and changed will become true (but we
                  # force it to false to not output a line saying
                  # "changed"), and msg will become "line added", else
                  # changed stays false, and msg does not contain "line
                  # added" (it contains "line replaced")
  lineinfile:
    dest: /etc/lvm/lvm.conf
    line: lvm.conf already has our rules present
    regexp: 'ANSIBLE_RULES_AFTER'
    state: present
  changed_when: false

- name: debug lvm_conf_ansible_marker_exists
  debug:
    msg: "lvm_conf_ansible_marker_exists = {{ lvm_conf_ansible_marker_exists.msg }}"

- name: "append ansible marker to lvm conf"
  when: (lvm_conf_ansible_marker_exists.msg == "line added")
  lineinfile:
    dest: /etc/lvm/lvm.conf
    backrefs: yes
    regexp: '^(\s*global_filter=.*)"\]'
    line: '\1", "r|ANSIBLE_RULES_AFTER|"]'
    state: present
  become: true

  # https://forum.proxmox.com/threads/disk-prevent-from-spinning-down-because-of-pvestatd.53237/
- name: disks presented through to other VMs blacklisted from local lvm
  lineinfile:
    dest: /etc/lvm/lvm.conf
    backrefs: yes
    regexp: '^(.*global_filter=.*, "r\|ANSIBLE_RULES_AFTER\|").*\]'
    line: '\1, "r|/dev/disk/by-id/scsi-(35000c50085b09ad3|35000039828122ce9|35000c5008580f107)|", "r|/dev/disk/by-id/ata-WUH(WUH721816ALE6L4_2CH6JXTJ|WUH721816ALE6L4_2CH83RBJ)|"]'
    state: present
  become: true

- name: turn off softdog watchdog reboot
  # I think this was in response to pve1 rebooting when I rebooted
  # pve2, because I was running 2 node cluster.  But I don't care for
  # protection against split-brain in my cluster.
  copy:
    content: "# ANSIBLE CONTROLLED\n# https://forum.proxmox.com/threads/how-to-disable-fencing-for-debugging.59625/\noptions softdog soft_noboot=1\n"
    dest: "/etc/modprobe.d/softdog.conf"
  become: true
  when: no_softdog_reboot is defined

- name: include after bootstrap tasks
  include_tasks: after_bootstrap.yml
  when: in_bootstrap is not defined

# FIXME: install QemuServer hook to call the guest hook
