---
- name: determine if enterprise pve subscription exists
  stat: path=/etc/apt/apt.conf.d/86pve-nags
  register: pve_enterprise_nag_buster

- name: ensure old pve community repository removed
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve buster pve-no-subscription
    state: absent
    filename: pve-community
  become: true

- name: copy pve-nag-buster/install.sh to pve
  copy:
    src: /home/tconnors/sysadmin/install/pve-nag-buster/install.sh
    dest: "/home/{{ ansible_env.USER }}/Downloads/pve-nag-buster-install.sh"
    mode: 0755

- name: install the pve nag buster
  command: /home/{{ ansible_env.USER }}/Downloads/pve-nag-buster-install.sh --offline
  when: not pve_enterprise_nag_buster.stat.exists
  become: true

- name: remove prohibited packages
  apt:
    name: ['os-prober']
    state: absent
  become: true

- name: Install proxmox tools
  apt:
    # https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Jessie
    name: ['proxmox-ve', 'ssh', 'postfix', 'ksm-control-daemon', 'open-iscsi', 'systemd-sysv', 'virt-goodies', 'munin-libvirt-plugins', 'swapspace']
    update_cache: yes
    cache_valid_time: 3600
    autoremove: no
    state: present
  become: true

- name: ensure SMR drives have a longer timeout
  copy:
     content: "ACTION==\"add\", SUBSYSTEM==\"block\",  ENV{ID_MODEL}==\"ST8000AS0002*\", RUN+=\"/bin/sh -c 'echo 60 > /sys/block/%k/device/timeout'\"\n"
     # find string with `udevadm test /sys/class/block/sdf`
     # also tells you whether it appended RUN appropriately
     dest: /etc/udev/rules.d/90-SMR-drive-timeout.rules
  become: true

- name: install suspend-all
  copy:
    src: ./src/pve_server/{{ item }}
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: 0755
  become: true
  with_items:
    - suspend-all

  # FIXME: there are no partitions on pve where there's enough space for swapspace to operate
- name: Ensures /var/lib/swapspace 0700
  file:
    path="/var/lib/swapspace"
    state=directory
    mode=0700
  become: true
