---
- name: restart battery-stats
  service:
    name: battery-stats
    state: restarted
  become: true

- name: restart network-keep-alive
  systemd:
    name: "network-keep-alive"
    state: restarted
    daemon_reload: yes
  become: true

