---
- name: Install /etc/genders
  copy:
    src: management/genders
    dest: /etc/genders
    owner: root
    group: root
    mode: 0644
  become: true

- name: Install turn-on-pve-backup, turn-off-pve-backup
  copy:
    src: "management/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  become: true
  with_items:
    - turn-on-pve-backup
    - turn-off-pve-backup

- name: Install management packages
  apt:
    name: ['pdsh', 'clusterssh']
    update_cache: yes
    cache_valid_time: 3600
    autoremove: no
    state: present
  become: true

- name: Make sure all handlers run
  meta: flush_handlers
