---
- name: Install /etc/genders
  copy:
    src: ./src/management/genders
    dest: /etc/genders
    owner: root
    group: root
    mode: 0644
  become: true

- name: Install management packages
  apt:
    name: ['pdsh', 'clusterssh']
    update_cache: yes
    cache_valid_time: 3600
    autoremove: no
    state: present
  become: true
