---
- name: Enable default set of repositories
  template:
    src: etc/apt/sources.list.{{ deb_release }}.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  become: true
  when: not (host_is_turnkey | default(false)) and not (host_is_still_debian_buster | default(false))

- name: Enable apt backports
  template:
    src: etc/apt/sources.list.d/backports.list.{{ deb_release }}.j2
    dest: /etc/apt/sources.list.d/backports.list
    owner: root
    group: root
    mode: 0644
  become: true
  when: host_has_backports | default(false)

- name: Enable apt testing repo
  template:
    src: etc/apt/sources.list.d/testing-unstable.list.j2
    dest: /etc/apt/sources.list.d/testing-unstable.list
    owner: root
    group: root
    mode: 0644
  become: true
  when: host_is_desktop | default(false)

- name: Enable apt stable pinning
  template:
    src: etc/apt/preferences.d/pin-0stabletesting.{{ deb_release }}.j2
    dest: /etc/apt/preferences.d/pin-0stabletesting
    owner: root
    group: root
    mode: 0644
  become: true

#- name: Update all packages
#  apt:
#    update_cache: yes
#    upgrade: safe
#    autoremove: no

- name: Make sure all handlers run
  meta: flush_handlers
