---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Enable default set of repositories
  copy:
    src: apt/sources.list.{{deb_release | default("bullseye")}}
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  become: true
  when: host_is_turnkey is not defined and host_is_pi is not defined and host_is_still_debian_buster is not defined

- name: Enable apt backports
  copy:
    src: apt/sources.list.d.backports.list.{{deb_release | default("bullseye")}}
    dest: /etc/apt/sources.list.d/backports.list
    owner: root
    group: root
    mode: 0644
  become: true
  when: host_has_backports is defined

- name: Enable apt stable pinning
  copy:
    src: apt/preferences.d.pin-0stabletesting.{{deb_release | default("bullseye")}}
    dest: /etc/apt/preferences.d/pin-0stabletesting
    owner: root
    group: root
    mode: 0644
  become: true

#- name: Update all packages
#  apt:
#    update_cache: yes
#    upgrade: safe
#    autoremove: no

