#!/bin/sh

### BEGIN INIT INFO
# Provides:          zramctrl
# Should-Start:      
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     S 0 1 2 3 4 5 6
# Default-Stop:      
# Short-Description: zramctrl stolen from https://aur.archlinux.org/packages.php?K=zramswap&SeB=x
# Description:       zramctrl stolen from https://aur.archlinux.org/packages.php?K=zramswap&SeB=x
### END INIT INFO


start() {
  exec awk '
  FILENAME == "/proc/cpuinfo" && $1 == "processor" {
    cpucount++
    next
  }

  FILENAME == "/proc/meminfo" && $1 == "MemTotal:" {
    mem_total = (0 + $2) * 1024
    next
  }

  END {
    mem_per_cpu = sprintf("%d", mem_total / cpucount)

    system("modprobe zram num_devices=" cpucount)

    for (i = 0; i < cpucount; i++) {
      print mem_per_cpu > "/sys/block/zram" i "/disksize"
      system("mkswap /dev/zram" i " -L zram" i)
      swapdevs = swapdevs " /dev/zram" i
    }

    system("swapon -d -p 100" swapdevs)
  }
  ' /proc/cpuinfo /proc/meminfo
}

stop() {
  exec awk '
  FNR > 1 && $1 ~ /^\/dev\/zram[0-9]+$/ {
    activeswaps = activeswaps " " $1
  }

  END {
    system("swapoff" activeswaps)
    system("rmmod zram")
  }
  ' /proc/swaps
}

case $1 in
  start|stop) "$1" ;;
esac
