all:
  children:
    laptops:
      hosts:
        fermi:
          fqdn: fermi.rather.puzzling.org
          hostname: fermi
          host_is_desktop: true
          host_is_physical: true
          host_is_amd: true
          host_is_laptop: true
          host_has_backports: true
          XKBMODEL: "inspiron"
        maxwell:
          fqdn: maxwell.rather.puzzling.org
          hostname: maxwell
          host_is_desktop: true
          host_is_physical: true
          host_is_intel: true
          host_is_laptop: true
        dirac:
          fqdn: dirac.rather.puzzling.org
          hostname: dirac
          host_is_virtual: true
          host_is_desktop: true
          host_is_zfs: true
#FIXME: no longer physical
#          host_is_physical: true
          host_is_legacy: true
          host_has_backports: true
          host_needs_no_spectre_mitigations: true
          host_is_mgmt: true
        dirac-laptop:
          fqdn: dirac-laptop.rather.puzzling.org
          hostname: dirac-laptop
          host_is_desktop: true
          host_is_physical: true
          host_is_intel: true
          host_is_laptop: true
          host_is_legacy: true
          host_has_backports: true
    containers:
      hosts:
        zm:
#          fqdn: zm.rather.puzzling.org
          hostname: zm
          host_is_container: true
        mail:
#          fqdn: mail.rather.puzzling.org
          hostname: mail
          host_is_container: true
          host_is_mailserver: true
        media:
          hostname: media
          host_is_container: true
#        homeassistant:
#          hostname: homeassistant
#          host_is_container: true # not strictly, but we don't want to go buggering around with the installation more than necessary
    desktops:
      hosts:
        pauli:
          fqdn: pauli.rather.puzzling.org
          hostname: pauli
          host_is_physical: true
          host_is_desktop: true
          host_has_backports: true
          host_is_intel: true
        dirac-new:
          fqdn: dirac-new.rather.puzzling.org
          hostname: dirac-new
          host_is_virtual: true
          host_is_desktop: true
          host_has_radeon: true
          host_has_backports: true
          host_needs_no_spectre_mitigations: true
          ssh_host_rsa_key_pub: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAwxeKtbN2I7BAFhxebq1UxbgjJi9A7okaww9SxlT2N2yNAdBnMo4YX1UgNLpZoFOYmP0ISr3F2ujGbE0L7tk3OAyNwdxO7llhkb5aHziDlzOJ9gspecr6s7VnHBIYdu+XP3nT9Vd17tdzOzhqx/TRSdoKCgb9M12NpAb6xs8/sn+ypoizUJUAOo4/Yf1EKuAjNPenmUz2n1YXYF/yqIgn1gV6jzSmYZsz6mWYbchKmWBKH27nRl8xRS2y8nCWDp1Z+lHfTQm4E8sa2Xvhk46DG01PWOugqw9R9gMY78EG1aiNldZaV7ReOuxCVQQftnA+TFYjST/E4zLrwJZxOyUk4Q== root@dirac
          ssh_host_ecdsa_key_pub: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJwodSOQQaUIaLLR/tiuyem605fwZYUwyd/ZX2VDYVnabg2v6If7xL3kx7VLq/KM1aJxuAsczyhbfYvNEUjXrVY= root@dirac
          ssh_host_ed25519_key_pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFZJOwqSOY735IP2J6S7CuNS4i90RAXX81pUof8EbXo2 root@dirac
          root_id_rsa_pub: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1ox/X4uwWJ9agYQIYZF/3JomqkNFjTzHQ8c+1odLWtpdGyU7JABLdHSMzMTqxnnyMW2oaqxtzhB2iAIgaIgt9LodCDyppJBwIGT81fofs5yQDnDm1BzJaRX09Fnbp20GJAWSdvYeChfcSOYEtauQwuLBiTSrTC7vi6AJN48E/wA4E1M3w57pnTLK3oPUaXdgXdOGwuMDyugl7wSvbZE++ewKlPu1omzsE0CocDE1hvBD95oT8O7z5OrWrmS7/sLLM9qaqQe8zHJVvqksr2IvtGgTZTsw1JHBTOqOQB5OTgwfAOfpWHB+4gkZKlGw9Uf10vGG7W5MtKz//9WT5g80j root@dirac-new
          root_authorized_keys: |
            ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAni+3/e/xdeHtk5g1nk2kAR1GkEEwje2uF7YZFUS0wmrcf1A3a9plNFuf41fEDNiqK/Ug4ijNIv+pFjJBFSHxR+syyC949O0mgxk+IRlORRlkpOh+zaqIPCZrj8+J7qN+yIJA0P6wtUzLgpwqDk3NuVWEt57OJB3ncChqEAfDDA7xWeFD9Fd6Iz+o1+BYmqT1DKJEdefLIrX9qYdSF9CUYCtN7A1pWEo+Ihc44EBxreC3pbz0R6FZPqd6nz3gqF1UKcTvZXjZxWzXVtr/RmG3Jy/j5VLEXl2x5U5XYQ7lcwbRGtemyf3Yt9V+PTjutQq70r4UJ+efU8Ky2M0F8sz7ww== tconnors@dirac
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1ox/X4uwWJ9agYQIYZF/3JomqkNFjTzHQ8c+1odLWtpdGyU7JABLdHSMzMTqxnnyMW2oaqxtzhB2iAIgaIgt9LodCDyppJBwIGT81fofs5yQDnDm1BzJaRX09Fnbp20GJAWSdvYeChfcSOYEtauQwuLBiTSrTC7vi6AJN48E/wA4E1M3w57pnTLK3oPUaXdgXdOGwuMDyugl7wSvbZE++ewKlPu1omzsE0CocDE1hvBD95oT8O7z5OrWrmS7/sLLM9qaqQe8zHJVvqksr2IvtGgTZTsw1JHBTOqOQB5OTgwfAOfpWHB+4gkZKlGw9Uf10vGG7W5MtKz//9WT5g80j root@dirac
###
    servers:
      hosts:
        fs:
          fqdn: fs.rather.puzzling.org
          hostname: fs
          host_is_virtual: true
          host_is_legacy: true
          host_has_backports: true
          host_is_fileserver: true
          host_is_zfs: true
          host_is_mgmt: true
        pi:
          fqdn: pi.rather.puzzling.org
          hostname: pi
          host_is_legacy: true
          host_is_pi: true
        hass-debian:
          fqdn: hass-debian.rather.puzzling.org
          hostname: hass-debian
          host_is_virtual: true
        fs-new:
          fqdn: fs.rather.puzzling.org
          hostname: fs
          host_is_virtual: true
          host_is_fileserver: true
          host_is_zfs: true
          host_is_mailserver: true
          ssh_host_rsa_key_pub:
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDEgKmem5wjy7Rc8shNABrThLaDFQQmXHPwNlrJlYWDOz+fcYfTcp1haGxpT5KPvKucm57+k0BsAS1p7+u+jhvDDmULcQfD1WPVM8QBz+h9a8Fz+/thDKok/292H2d9RERHQ3KlTNnAutU39R8fqvgd/lyAl2/BLpCWqKGvITQIyD0QpLOQyBWiJlGTf+ubUq4bhTsCj4k3/S93y9rUlL9rYztTX1BhZscWY0IdPHcKWOwOij3gySGvtF7F4kJJL8hH/cTRyEwlJFQDGU/0hMxmPBK03xVKCof8F9kO3sMX6p166t5kFB6CErWMEVy9fF2gONOxK1vAjRPV6jIJACt root@fs
          ssh_host_ecdsa_key_pub: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAXUG8WAzABE7PB20fnzmX1YZjrOtEOlkJOyd1sM3rqShPQ2NWNehgMMzmy/Sov9sTPKBwCvz5h3x9kFiNM4vmM= root@fs
          ssh_host_ed25519_key_pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILh+oFev4KL6WtjH3wq3KYs0KH/QQFvJFxo/xgcxzpnZ root@fs
          root_id_rsa_pub: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAoJ65rWsr2zuaY/936uOuWD3aTq6Mdztvb6hxzR6sK9yUSY9BlNVPFS7E0wilY/PBihpDPtueAjzRlbR+In+azPDJ9OD9kYIG8d+MavU6JPbD8wjq2vo0MPw3krhIqEWiSED6yMS4M0vvhL0UoUPR1rM2oROlqjGq1Ag/VCHUlYdkgC8ZTVWTaqbiTIzwsVFobQOR9g8MkF7KewDJQhvD1+OOuSMmpO5vm8sR+JMUODCPx+Xc7NCSpKyBa3Pxrxf1KlLCLiknXviY7tFNy1mscAwFDszdNFNatavLFEG1LipOck2ETDTdsWIH0xwHweEhta/QAv0w46QftkrdDp4Zqw== root@fs-new
          root_authorized_keys: |
            ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAoJ65rWsr2zuaY/936uOuWD3aTq6Mdztvb6hxzR6sK9yUSY9BlNVPFS7E0wilY/PBihpDPtueAjzRlbR+In+azPDJ9OD9kYIG8d+MavU6JPbD8wjq2vo0MPw3krhIqEWiSED6yMS4M0vvhL0UoUPR1rM2oROlqjGq1Ag/VCHUlYdkgC8ZTVWTaqbiTIzwsVFobQOR9g8MkF7KewDJQhvD1+OOuSMmpO5vm8sR+JMUODCPx+Xc7NCSpKyBa3Pxrxf1KlLCLiknXviY7tFNy1mscAwFDszdNFNatavLFEG1LipOck2ETDTdsWIH0xwHweEhta/QAv0w46QftkrdDp4Zqw== root@dirac
###
        enclosure:
          fqdn: enclosure.rather.puzzling.org
          hostname: enclosure
          host_is_physical: true
          host_is_intel: true
#          host_is_enclosure: true
          inet_addr: 192.168.1.7
          # old enclosure hardware:
          #mac_addr: 00:14:fd:16:21:c4
          mac_addr: 70:54:d2:90:a2:52
          host_is_pve_server: true
          host_is_in_pve_cluster: true
        pve:
          fqdn: pve.rather.puzzling.org
          hostname: pve
          inet_addr: 192.168.1.5
          mac_addr: f0:1f:af:d9:75:20
          host_is_physical: true
          host_is_dell_server: true
          host_is_intel: true
          host_is_pve_server: true
          host_is_zfs: true
          host_is_in_pve_cluster: true
          vfio_ids: "ids=8086:1d2d,8086:1d26" # obtain with:
#          vfio_ids: "ids=1002:699f,1002:aae0,1022:43ee" # obtain with lspci -nvvv | grep -e VGA\ controller -e XHCI -e 1002
#          host_has_backports: true
          ssh_host_rsa_key_pub: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMtszldmL5KLgZeUe3JUe54IfFLNRlAZrAnMOruAiIuyk2wGwf8Ho5baCsXqxXsox/b85pE8iJUN457pTe6frkk2FBC6LnomUYRJ6QFU8l+lUutz3qmwrVTz7OXE/nTEz+NoFy4uF2xtD3WrGW71sVMO96eiJUPkaYxVlJNN3aZXpC+JgZanYLvTEm/LTOgGOgnoeOIeZkmB2omxcpW3lEnT9+qzdFxgdIliDwu6HtL6teJjuitTpurNa8z5aZqO+HCTRW4uHhWmIBxaXSCe7Z80H/pTcbwoIpMmOooE8gybDgEpXOEVOaxmZL8AEblWlBlo3EfzgAXLyUM+/oh1v7 root@pve
          ssh_host_ecdsa_key_pub: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGLUmY3URRHdEJ/a8xLFLLYokRNAg3ug8VoX9f68NnWdSYnxrh8lxLrEKVTBIKOUHS/q7vuxxQNY1kO3QMPYA1s= root@pve
          ssh_host_ed25519_key_pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFdOseGruzEKLA1V94ratCN90BFNeBvypSfezIxljevH root@pve
        pve2:
          fqdn: pve2.rather.puzzling.org
          hostname: pve2
          inet_addr: 192.168.1.6
          mac_addr: 04:42:1a:2d:76:29
          host_is_physical: true
          host_is_amd: true
          host_is_pve_server: true
          host_is_zfs: true
          host_is_in_pve_cluster: true
          host_needs_no_spectre_mitigations: true
          vfio_ids: "ids=1022:149c,1002:67df,1002:aaf0,1022:43ee,1022:1487" # obtain with:
          # for d in /sys/kernel/iommu_groups/*/devices/*; do
#n=${d#*/iommu_groups/*}; n=${n%%/*}
#    printf 'IOMMU Group %s ' "$n"
#    lspci -nns "${d##*/}"
#done | grep --color -i -e USB -e VGA\ co -e XHCI -e Audio -e 'IOMMU Group 13' -e 'IOMMU Group 2[3489]' -e 1022:149c -e 1002:67df -e 1002:aaf0 -e 1022:43ee -e 1022:1487
#          host_has_backports: true
          ssh_host_rsa_key_pub: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDaKgXeqwkkw+tlnbUSA34MwHUtnghtsyHkQyOfdgJL5K8ezKEijkECNPdMheBDKHTB5L2KNxekh2mN3OS3l3i8yvteDEhXlOiQDip1kdlUPXydo9lAunIIwxUZX40AKjEY8iOwwHGSevGuBfHDjdiUh9DCtWobW2BbH7dhC9fX6u3x5RG28TCkdmjLUqahAVxmhw3wv/B9TBYq1Rn9ydFUGgwvMVM+1eAqxthn5ISSHuhK0aLUfrgsjz6tjDGGLFtrTOgDbKG2JeDIYG/jyD57OP9Ht3x1WAJmoSN4LJ2upXHUQubA2tmuZbgfgEZXtkTWaYLqulcP829tpR/9VfnWjqR0/KllPPdDQv3j+2w5ra7DeeqY+UVyC6GCTHykQZu7TGpl/N8h/yEEFm2ALTrqDcRWfN5clt/+aGUYwu/Vsb/esWRAJCmP7GlYz3Z87X/REHsV6xn+1k/X08x6KuHdJqcJB8gsn8aJIZ7qKRSyoMUVJMvuNS3CnZOyzUaJnSU= root@pve2
          ssh_host_ecdsa_key_pub: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLGQtLolSQw13PGsfTlDdvJfoREUmqNK7rHyvfv3z9CciLFXK6T907Go+B13kvSuvJG2XfKivp4o+yOC3NFmrJc= root@pve2
          ssh_host_ed25519_key_pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHnUkqwxjgCpOpHaTCebqo79dKlPM5U7yiYKP7e+RdKM root@pve2
    openwrt:
      hosts:
        b1300:
          type: router
          openwrt_heavy_installation: true
          openwrt_router_packages: true
        archerc7:
          type: ap
          openwrt_heavy_installation: true
        archerd7:
          type: ap
          openwrt_heavy_installation: true
        wavlink:
          type: ap
          # allowed since we offloaded big files to NFS:
          openwrt_heavy_installation: true
        re450:
          type: ap

