all:
  children:
    laptops:
      hosts:
        fermi:
          fqdn: fermi.rather.puzzling.org
          hostname: fermi
    desktops:
      hosts:
        pauli:
          fqdn: pauli.rather.puzzling.org
          hostname: pauli
    servers:
      hosts:
        r520:
          fqdn: r520.rather.puzzling.org
          hostname: r520
