---
# https://stackoverflow.com/questions/18195142/safely-limiting-ansible-playbooks-to-a-single-machine
- hosts: '{{ target | default(all) }}'
  remote_user: ansible

  vars_files:
    - vars/main.yml

  roles:
    - essentials
    - hostname
    - user
    - logs
    # pve_server is loaded in bootstrap.yml as well, but that's just to make sure all the repos are there.  No harm updating that here as time goes on
    - role: fileserver
      when: host_is_fileserver is defined
    - role: mailserver
      when: host_is_mailserver is defined
    - role: pve_server
      when: host_is_pve_server is defined
    - role: virtual
      when: host_is_virtual is defined
    - role: physical
      when: host_is_physical is defined
    - role: laptop
      when: host_is_laptop is defined
    - role: dell_server
      when: host_is_dell_server is defined
    - role: desktop
      when: host_is_desktop is defined
    - fail2ban
    - ssh
    - monitoring
#    - zsh
#    - newrelic
#    - ufw
