---
# https://stackoverflow.com/questions/18195142/safely-limiting-ansible-playbooks-to-a-single-machine
- hosts: "iot"
  gather_facts: no
  remote_user: ansible_adm
  roles:
    - role: munin-server
      when: inventory_hostname == 'iot'

# to do a quick sync of commonly changed files, let's just push them
# first without running a slow gather_facts first:
- hosts: "{{ target | default('all,!openwrt,!tasmota') }}"
  remote_user: ansible_adm
  gather_facts: no
  vars_files:
    - vars/main.yml
  roles:
    - role: common_handlers
      become: true # the whole role, including handlers, will become root
    - install_files

- hosts: "{{ target | default('all,!openwrt,!tasmota') }}"
  remote_user: ansible_adm
#  gather_facts: no  # when doing a very quick debug run
  vars_files:
    - vars/main.yml
  roles:
    - role: common_handlers
      become: true # the whole role, including handlers, will become root
    - role: bootstrap
    - role: ssh_bootstrap
      become: true
    - role: webserver
      when: host_is_web_server is defined
    - role: nutserver
      when: (host_is_nut_server is defined) or (host_is_nut_master is defined)
    - role: nutmaster
      when: host_is_nut_master is defined
    - role: management
      when: host_is_mgmt is defined
    - user
    - apt_repos
    - essentials
    - monitoring
    - role: spectre_mitigations_disabled
      when: host_is_container is not defined and host_is_pi is not defined
    - role: hostname
      when: host_is_container is not defined
    - role: fileserver
      when: host_is_fileserver is defined
    - role: mailserver
      when: host_is_incoming_mailserver is defined
    - role: smtp
    # pve_server is loaded in bootstrap.yml as well, but that's just
    # to make sure all the repos are there.  No harm updating that
    # here as time goes on
    - role: pve_server
      when: host_is_pve_server is defined
    - role: virtual
      when: host_is_virtual is defined
    - role: physical
      when: host_is_physical is defined
    - role: laptop
      when: host_is_laptop is defined
    - role: dell_server
      when: host_is_dell_server is defined
    - role: desktop
      when: host_is_desktop is defined
    - role: ssh
    - role: fail2ban
    - role: power_saving
