---
# https://stackoverflow.com/questions/18195142/safely-limiting-ansible-playbooks-to-a-single-machine
- hosts: "iot"
  gather_facts: no
  remote_user: ansible_adm
  roles:
    - role: munin-server
      when: inventory_hostname == 'iot'

- hosts: "{{ target | default('all,!openwrt,!tasmota') }}"
  remote_user: ansible_adm
#  gather_facts: no  # when doing a very quick debug run
  vars_files:
    - vars/main.yml
  roles:
    - role: common_handlers
      become: true # the whole role, including handlers, will become root
    - monitoring
