---
- hosts: "{{ target | default('all,!openwrt,!tasmota') }}"
  remote_user: "{{ ssh_user | default('ansible_adm') }}"
#  gather_facts: no  # when doing a very quick debug run
  vars_files:
    - vars/main.yml
  roles:
    - role: common_handlers
      become: true # the whole role, including handlers, will become root
    - install_user_files
