---
# https://stackoverflow.com/questions/18195142/safely-limiting-ansible-playbooks-to-a-single-machine
- hosts: "{{ target | default('all,!openwrt,!tasmota') }}"
  remote_user: ansible_adm
#  gather_facts: no  # when doing a very quick debug run
  vars_files:
    - vars/main.yml
  roles:
    - role: webserver
      when: host_is_web_server is defined
