---
# https://stackoverflow.com/questions/18195142/safely-limiting-ansible-playbooks-to-a-single-machine
- hosts: "{{ target | default('all,!openwrt,!tasmota,!work') }}"
  remote_user: "{{ ssh_user | default('ansible_adm') }}"
#  gather_facts: no  # when doing a very quick debug run
  vars_files:
    - vars/main.yml
  roles:
    - role: common_handlers
      become: true # the whole role, including handlers, will become root
    - role: pve_server
      when: host_is_pve_server | default(false)
