---
# https://stackoverflow.com/questions/18195142/safely-limiting-ansible-playbooks-to-a-single-machine
- hosts: "{{ target | default('openwrt') }}"
  strategy: free
#  gather_facts: no
  remote_user: rootsh # so keeps working even fresh after upgrade (but not brand-new installation)
#  vars_files:
#    - vars/main.yml
  roles:
    - gekmihesg.openwrt
    - openwrt
