---
# https://stackoverflow.com/questions/18195142/safely-limiting-ansible-playbooks-to-a-single-machine
- hosts: "{{ target | default('openwrt') }}"
#  strategy: free
  strategy: linear
#  gather_facts: no
  remote_user: "{{ remote_user | default('rootsh') }}" # so keeps working even fresh after upgrade, but not on a brand-new installation - supply '-e remote_user=root' for a new installation
  vars:
      ansible_ssh_transfer_method: scp
  vars_files:
    - vars/openwrt.yml
  roles:
    - gekmihesg.openwrt
    - install_files
    - openwrt
