---
# https://stackoverflow.com/questions/18195142/safely-limiting-ansible-playbooks-to-a-single-machine
- hosts: "{{ target | default('openwrt') }}"
#  strategy: free
  strategy: linear
#  gather_facts: no
  remote_user: rootsh # so keeps working even fresh after upgrade (but not brand-new installation)
  vars:
      ansible_ssh_transfer_method: scp
      ansible_scp_extra_args: -O #https://github.com/gekmihesg/ansible-openwrt/pull/59 https://github.com/gekmihesg/ansible-openwrt/issues/64 https://github.com/ansible/ansible/issues/82239 https://github.com/gekmihesg/ansible-openwrt/pull/67
      run_uci_config: yes
  vars_files:
    - vars/openwrt.yml
  roles:
    - gekmihesg.openwrt
    - install_files
    - openwrt
