---
- hosts: test
  user: vagrant
  become: true

  vars_files:
    - vars/main.yml

  roles:
    - essentials
    - hostname
    - user
    - logs
    - spectre_mitigations_disabled
    - fail2ban
    - ssh
    - monitoring
