---
# https://stackoverflow.com/questions/18195142/safely-limiting-ansible-playbooks-to-a-single-machine
- hosts: '{{ target }}'
  remote_user: ansible

  vars_files:
    - vars/main.yml

  tasks:
    # FIXME: HOWTO: add a list to a parameter
    - name: "Search for docker grub config"
      become: yes
      register: docker_grub_cmdline
      check_mode: yes # cause this to become just a test.  If there's already
                      # user_namespace settings, then this will think line is
                      # being replaced, and changed will become true (but we
                      # force it to false to not output a line saying
                      # "changed"), and msg will become "line added", else
                      # changed stays false, and msg does not contain "line
                      # added"
      lineinfile:
        dest: /tmp/grub
        line: grub cmdline already has namespace enabled
        regexp: "^GRUB_CMDLINE_LINUX_DEFAULT=.*user_namespace.enable=1 namespace.unpriv_enable=1"
        state: present
      changed_when: false

    - name: "Append docker grub config"
      when: docker_grub_cmdline.msg == "line added"
      lineinfile:
        dest: /tmp/grub
        backrefs: yes
        regexp: "^GRUB_CMDLINE_LINUX_DEFAULT=\"(.*)\""
        line: "GRUB_CMDLINE_LINUX_DEFAULT=\"\\1 user_namespace.enable=1 namespace.unpriv_enable=1\""
        state: present
      become: true

