---
# https://stackoverflow.com/questions/18195142/safely-limiting-ansible-playbooks-to-a-single-machine
- hosts: "{{ target | default('all,!openwrt,!tasmota,!work') }}"
  remote_user: "{{ ssh_user | default('ansible_adm') }}"
#  gather_facts: no  # when doing a very quick debug run
  vars_files:
    - vars/main.yml
  vars:
    - in_bootstrap: true
  roles:
    - apt_repos
    - pve_server
