---
- name: Install authorized_keys for {{ item }}
  authorized_key:
    user: "{{ item.key }}"
    key: "{{ key }}"
    state: "{{ item.value.state }}"
    # if user doesn't have a home directory, just dump the key into /tmp and otherwise let the system ignore it
    path: "{{ getent_passwd[item.key][4] is defined | ternary(omit, '/tmp/' ~ item.key ~ '_ssh_authorized_keys') }}"
    #    comment: "{{ item.value.comment }}"
  loop_control:
    loop_var: key
  with_items: "{{ item.value.sshkeys }}"
  become: true
