---
- name: Install mailserver packages
  apt:
    name: ['postfix']
    update_cache: yes
    cache_valid_time: 0
    autoremove: no
    state: present
  become: true

- name: Make sure all handlers run
  meta: flush_handlers

# FIXME: Still to be fleshed out...  Needs to set up a properly hardened mailserver, firewalled off, selinux, etc...
