---
- name: setup a munin.conf entry for each linux, openwrt node
  template:
    src: munin-local.conf.j2
    dest: /etc/munin/munin-conf.d/local.conf
  become: true

- name: Install munin prereq packages
  apt:
    name:
      - 'rrdcached'
      - 'acl'
    autoremove: no
    state: present
    install_recommends: no
  become: true

- name: setup systemd overrides
  copy:
    src: "etc/systemd/system/{{ item }}.d/override.conf"
    dest: "/etc/systemd/system/{{ item }}.d/"
  with_items:
    - rrdcached.service
  become: true
  notify: restart systemd overrides

- name: Install munin packages
  apt:
    name:
      - 'munin'
    autoremove: no
    state: present
    install_recommends: no
  become: true

- name: install munin server plugins onto munin server
  copy:
    src: monitoring/munin/{{ item }}
    dest: /etc/munin/plugins/{{ item }}
    owner: root
    group: root
    mode: 0755
    local_follow: true
  become: true
  with_items:
   - rrdcached
  notify: restart munin-node

- name: Make sure all handlers run
  meta: flush_handlers
