---
- name: "Update initramfs config"
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/update_initramfs_config.yml"

- name: "Regenerate boot config"
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/regenerate_boot_config.yml"
