---
- name: "Regenerate grub config"
  shell: "proxmox-boot-tool refresh" # not meant to use update-grub
  become: true

- name: "Update initramfs config"
  shell: "/usr/sbin/update-initramfs -u -k all"
  become: true

- name: "reload cron"
  service:
    name: cron
    state: restarted
  become: true
