#!/bin/bash

if ! grep non-free-firmware /etc/apt/sources.list | grep ' non-free ' ; then
    # make sure non-free and contrib repos are enabled
    sed -i 's/non-free-firmware/non-free non-free-firmware contrib/' /etc/apt/sources.list
fi

apt update
apt dist-upgrade

apt install less most x11-utils xdm ssh man vim git xterm procmail curl keychain mgitstatus rsync telnet vim-pathogen plocate bash-completion net-tools lsof ncal x11-apps x11-xserver-utils lynx bind9-dnsutils tcpdump snapd mesa-utils dlocate apt-file iperf3 snapd dstat firefox-esr bc ksh fvwm vim-gtk3 wget gcc strace netcat-openbsd dlocate dos2unix gnupg ssh-askpass xcompmgr ansible ansible-mitogen gnuplot-qt w3m cryptsetup cryptsetup-initramfs cryptmount
# dnsmasq systemd-resolved

apt install -t bookworm-backports emacs emacs-gtk elpa-session elpa-yaml-mode

update-locale LANG=en_AU.UTF-8 LANGUAGE=en_AU:en LC_ALL

if ! [ -e /etc/sysctl.d/10-local.conf ] || ! md5sum /etc/sysctl.d/10-local.conf | grep 6fdd26992c003616c724e05e6e5719fe ; then
    echo kernel.dmesg_restrict = 0 > /etc/sysctl.d/10-local.conf
fi


if ! [ -e /etc/ssh/sshd_config.d/local.conf ] || ! md5sum /etc/ssh/sshd_config.d/local.conf | grep 1ef3493504a55c88f59511289c418628 ; then
    echo -e 'Port 6022\nListenAddress 0.0.0.0' | tee /etc/ssh/sshd_config.d/local.conf
    systemctl restart ssh
fi
# when we've remapped caps to ctrl in windows via autohotkey,
# CAPS turns on when caps is pressed, but can't be turned off again.  This doesn't fix it:
if ! grep ctrl:nocaps /etc/default/keyboard ; then
    sed -i 's/^XKBOPTIONS=.*/XKBOPTIONS="ctrl:nocaps,terminate:ctrl_alt_bksp,compose:rwin"/' /etc/default/keyboard
fi

if [ -e ~tconnors/.bash_logout ] ; then
    mv ~tconnors/.bash_logout ~tconnors/.bash_logout.orig
fi

virt=$( uname -r ; dmidecode -t1 )
case "$virt" in
    *WSL*)
        #apt install xdm
        #if ! tail -n 1 /etc/X11/xdm/Xaccess | grep "CHOOSER BROADCAST" ; then
        #    echo "*              CHOOSER BROADCAST       #any indirect host can get a chooser" >> /etc/X11/xdm/Xaccess
        #fi
        # don't think xdmcp chooser is a viable option since needs udp and can't forward that on to the container
        apt install xrdp xinput rxvt-unicode fonts-freefont-ttf x2goserver # tightvncserver - can't find a client that passes through as many keystrokes as rdp; x2goserver has same line-drawing and ANSI characters being injected into input buffer problem as xrdp
        update-rc.d ssh enable
        /etc/init.d/ssh restart

        if ! [ -e /etc/systemd/system/xrdp.service.d/override.conf ] || ! /etc/systemd/system/xrdp.service.d/override.conf | grep md5sum b241d6057cfaa6b27ae34140b25abe5a ; then
            # https://github.com/microsoft/WSL/issues/9303
            mkdir -p /etc/systemd/system/xrdp.service.d/
            echo -e '[Service]\nExecStartPre=/usr/bin/mount -o remount,rw /tmp/.X11-unix' | tee /etc/systemd/system/xrdp.service.d/override.conf
        fi
        if ! [ -e /etc/wsl.conf ] || ! md5sum /etc/wsl.conf | grep eb6e01d7002319c6f962662403def9e9 ; then
            echo -e '[boot]\nsystemd=true' | tee /etc/wsl.conf
        fi
        ;;
    *VirtualBox*)
        apt install xorg fvwm xdm xinput rxvt-unicode fonts-freefont-ttf

        # http://wiki.debian.org/VirtualBox#Oracle_Virtualbox_third-party_repository
        if [ ! -e /etc/apt/sources.list.d/backports.list ] ; then
            echo "deb http://ftp.au.debian.org/debian $(lsb_release -cs)-backports main non-free non-free-firmware contrib" > /etc/apt/sources.list.d/backports.list
            apt update
        fi
        apt install fasttrack-archive-keyring
        if [ ! -e /etc/apt/sources.list.d/fasttrack.list ] ; then
            echo "deb http://fasttrack.debian.net/debian-fasttrack/ $(lsb_release -cs)-fasttrack main contrib" > /etc/apt/sources.list.d/fasttrack.list
            echo "deb http://fasttrack.debian.net/debian-fasttrack/ $(lsb_release -cs)-backports-staging main contrib" >> /etc/apt/sources.list.d/fasttrack.list
            apt update
        fi
        if [ ! -e /etc/apt/sources.list.d/virtualbox.list ] ; then
            echo "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" > /etc/apt/sources.list.d/virtualbox.list
            wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | apt-key add -
        fi

        # None of this may be necessary if we find we having a working system upon reverting to snapshot:
        # FIXME: any need to enable testing repo at low priority?

        # FIXME: if this works, revert the snapshot and try the
        # packages again without manually installing through the ISO.

        # FIXME: have installed kernel backports.

        # FIXME: or maybe I can just deal with the xdm display bug in
        # default vmware driver, and I think xrandr -s 1920x1080
        # perhaps in combination with xcompmgr lets me run with no
        # display problems anyway?

        apt install virtualbox-guest-x11

        apt install linux-headers-amd64
#        apt install virtualbox-dkms --no-install-recommends
#        apt install virtualbox-ext-pack --no-install-recommends  # FIXME: trial license - most likely not needed so will remove
#        apt install virtualbox-guest-additions-iso # --no-install-recommends

#        mkdir /mnt/vbox
#        mount /usr/share/virtualbox/VBoxGuestAdditions.iso /mnt/vbox
#        /mnt/vbox/VBoxLinuxAdditions.run

        usermod -aG vboxsf tconnors   # get shared filesystem for windows
        ;;
    *)
        echo "Unknown virtualisation: $virt"
        ;;
esac

systemctl start plocate-updatedb.service &
