#!/bin/bash

~/windows-home/Downloads/install/wfreerdp.3.2.0-ia32.exe /w:1920 /h:1027 +mouse-relative /v:172.20.166.241 &

# can try "/clipboard:use-selection:PRIMARY" to interact with the
# PRIMARY rather than CLIPBOARD selections.  Would have to change our
# .Xdefault xterm bindings back
