---
# installs arrays of files

#- debug: msg="bashrc_files = {{ bashrc_files }}"
#- debug: msg="install_files = {{ install_files }}"
#- debug: msg="remove_files = {{ remove_files }}"

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: install list of directories
  file:
    path: "{{ item.dir }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items: "{{ install_dirs | default([]) }}"
  become: "{{ item.become | default(true) }}"
  when: item.when | default("true")

- name: install list of files
  include_tasks: install_list_files.yml
  loop: "{{ install_files | default([]) }}"
  loop_control:
    loop_var: file_details
    # allow user to supply when and when_pkg_installed -
  when: (file_details.when | default("true")) and ((file_details.when_pkg_installed | default("base-files")) in ansible_facts.packages)

- name: remove files not in list
  include_tasks: remove_list_files.yml
  loop: "{{ remove_files | default([]) }}"
  loop_control:
    loop_var: file_details
  when: file_details.when | default("true")
