---
# installs arrays of files

#- debug: msg="bashrc_files = {{ bashrc_files }}"
#- debug: msg="install_files = {{ install_files }}"
#- debug: msg="remove_files = {{ remove_files }}"

- name: install list of directories
  file:
    path: "{{ item.dir }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items: "{{ install_dirs }}"
  become: true

- name: install list of files
  include_tasks: install_list_files.yml
  loop: "{{ install_files }}"
  loop_control:
    loop_var: file_details

- name: remove files not in list
  include_tasks: remove_list_files.yml
  loop: "{{ remove_files }}"
  loop_control:
    loop_var: file_details
