---
# - name: install {{ file_details.source }}
#   copy:
#     src: "{{ file_details.source }}"
#     dest: "{{ file_details.dest }}"
#     mode: "{{ file_details.mode }}"
#   become: true
#   when: file_details.source is defined

- name: find all files but {{ file_details.files_not | default([]) }} from {{ file_details.dir }}
  find:
    paths: "{{ file_details.dir }}"
    file_type: file
    excludes: "{{ file_details.files_not }}"
  become: "{{ file_details.become | default(true) }}"
  register: files_to_delete
  when: file_details.files_not is defined

- name: remove {{ files_to_delete.files | map(attribute='path') }} from {{ file_details.dir }}
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ files_to_delete.files | map(attribute='path') | sort }}"
  become: "{{ file_details.become | default(true) }}"
  when: file_details.files_not is defined
  notify: "{{ file_details.notify | default(omit) }}"

- name: remove {{ file_details.files | default([]) }} from {{ file_details.dir }}
  file:
    path: "{{ file_details.dir }}/{{ item }}"
    state: absent
  with_items: "{{ file_details.files | default([]) | sort }}"
  become: "{{ file_details.become | default(true) }}"
  notify: "{{ file_details.notify | default(omit) }}"
