---
# delete contents of directory .name, where files exist in .source,
# defaulting to homes/<name> if .source isn't provided.  Intended so
# you can move a file in the source repo from <install_files> to
# <remove_files> and have a file that was previously installed per
# matching criteria, to now being removed

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/calculate_directory_contents.yml"

- name: "remove file under directory: {{ dir_file_or_template.name }} based on {{ source }}"
  file:
    path: "{{ dir_file_or_template.name }}{{ file_recurse.path }}"
    state: absent
  loop_control:
    loop_var: file_recurse
    label: "{{ dir_file_or_template.name }}{{ file_recurse.path }}"
  with_items: "{{ file_list.file }}"  # kinda want to remove directories too, but we wouldn't want to try to remove all parent directories!
  become: "{{ dir_file_or_template.become | default(true) }}"
  notify: "{{ dir_file_or_template.notify | default(omit) }}"
