---
- name: restart sysctl
  service:
    name: procps
    state: restarted
  become: true

- name: restart smartmontools
  service:
    name: smartmontools
    state: restarted
  become: true

- name: Reconfigure locales
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/locale.gen"
    - "/etc/default/locale"
  notify: dpkg-reconfigure locales
  become: true

- name: dpkg-reconfigure locales
  shell: dpkg-reconfigure --frontend noninteractive locales
  become: true

- name: Reconfigure tzdata
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/localtime"
    - "/etc/timezone"
  notify: dpkg-reconfigure tzdata
  become: true

- name: dpkg-reconfigure tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata
  become: true

- name: restart systemd overrides
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
  become: true
  with_items: "{{ systemd_overrides }}"
  ignore_errors: yes # for those units that aren't defined on this system
