---
- name: restart sysctl
  service:
    name: procps
    state: restarted
  become: true

- name: restart systemd-logind
  service:
    name: systemd-logind
    state: restarted
  become: true

- name: Reconfigure locales
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/locale.gen"
    - "/etc/default/locale"
  notify: dpkg-reconfigure locales
  become: true

- name: dpkg-reconfigure locales
  shell: dpkg-reconfigure --frontend noninteractive locales
  become: true

- name: Reconfigure tzdata
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/localtime"
    - "/etc/timezone"
  notify: dpkg-reconfigure tzdata
  become: true

- name: dpkg-reconfigure tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata
  become: true
