---
- name: restart sysctl
  service:
    name: procps
    state: restarted
  become: true

- name: restart smartmontools
  service:
    name: smartmontools
    state: restarted
  become: true

- name: Reconfigure locales
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/locale.gen"
    - "/etc/default/locale"
  notify: dpkg-reconfigure locales
  become: true

- name: dpkg-reconfigure locales
  shell: dpkg-reconfigure --frontend noninteractive locales
  become: true

- name: Reconfigure tzdata
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/localtime"
    - "/etc/timezone"
  notify: dpkg-reconfigure tzdata
  become: true

- name: dpkg-reconfigure tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata
  become: true

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
  become: true

- name: restart network-manager
  systemd:
    name: NetworkManager
    state: restarted
  become: true

- name: activate systemd timer
  systemd:
    name: warn-unattended.timer
    state: started
    enabled: yes
    daemon_reload: yes
  become_user: root
  become: true

- name: restart unattended-upgrades
  systemd:
    name: unattended-upgrades
    state: restarted
  become: true
  when: unattended_upgrades | default(true)
