#!/bin/bash

# usage: pve-restart-lxc <hostname>
# will determine if that machine is running, and if so, force stop it and restart
# performs no action is not already running

# other ideas: zmc is dying of OOM on pve1:zm ; monitor that as well as possibly automatically (hard) stop/start zm when health check is triggered, particularly if ipmi_power is detected > ???W

current_state() {
    lxcs=$( timeout -k 1 3 pct list | sed "s/^/$pve /" )

    read id state hostname < <( echo "$lxcs" | grep "\\s$host\\s*$" )
}

if [ "$#" != 1 ] ; then
    echo "Usage: $0 <hostname>" 1>&2
    exit 1
fi

host="$1"

current_state

if [ -n "$id" ] ; then
    if [ "$state" = running ] ; then
        echo "Attempt stop of $hostname: $id"
        pct stop "$id" || exit 1
        attempt=1
        current_state
        while ( [ -z "$state" ] || [ "$state" = running ] ) && [ "$attempt" -lt 20 ] ; do
            sleep 1
            current_state
            attempt=$((attempt+1))
            echo -n .
        done
        if [ "$state" = stopped ] ; then
            echo "Attempt start of $hostname: $id"
            pct start "$id"
        else
            echo "lxc $id in unexpected state after stopping; not starting: $state"
        fi
    else
        echo "lxc $id in unexpected state; not stopping and restarting: $state"
    fi
else
    echo "lxc $host not found in pct output:"
    echo "$lxcs"
fi
