---
- name: Disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    # pve in cluster mode automatically enables PermitRootLogin
    line: "{{ host_is_in_pve_cluster is defined | ternary ('PermitRootLogin yes', 'PermitRootLogin no # ANSIBLE CONFIGURED') }}"
    state: present
  notify: restart ssh
  become: true

#- name: Disable password authentication
#  lineinfile:
#    dest: /etc/ssh/sshd_config
#    regexp: '^PasswordAuthentication'
#    line: "PasswordAuthentication no"
#    state: present
#  notify: restart ssh

#- name: Only allow SSH access for the newly created user
#  lineinfile:
#    dest: /etc/ssh/sshd_config
#    insertafter: '^StrictModes'
#    line: "AllowUsers {{ user }}"
#    state: present
#  notify: restart ssh
