---
- name: Disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    # pve in cluster mode automatically enables PermitRootLogin
    line: "{{ ( ( host_is_in_pve_cluster | default(false) ) or ( permit_root_login | default(false) ) ) | ternary ('PermitRootLogin yes # ANSIBLE CONFIGURED', 'PermitRootLogin no # ANSIBLE CONFIGURED') }}"
    state: present
  notify: restart ssh
  become: true

- name: ensure /etc/ssh/{ssh_config.d,sshd_config.d} sourced
  lineinfile:
    dest: "{{ item }}"
    line: "Include {{ item }}.d/*.conf"
    insertbefore: ^[A-Za-z]
    firstmatch: true
  when: item != omit
  # trick from https://docs.ansible.com/ansible/latest/playbook_guide/complex_data_manipulation.html
  with_items:
    - "/etc/ssh/ssh_config"
    - "{{ (deb_release == 'buster') | ternary (omit, '/etc/ssh/sshd_config') }}"
  notify: restart ssh
  become: true

#- name: Disable password authentication
#  lineinfile:
#    dest: /etc/ssh/sshd_config
#    regexp: '^PasswordAuthentication'
#    line: "PasswordAuthentication no"
#    state: present
#  notify: restart ssh

#- name: Only allow SSH access for the newly created user
#  lineinfile:
#    dest: /etc/ssh/sshd_config
#    insertafter: '^StrictModes'
#    line: "AllowUsers {{ user }}"
#    state: present
#  notify: restart ssh
