---
- name: gather and implement munin {{ munin_plugin }} suggests
  become: yes
  register: suggests
  check_mode: no # even in --check, we want this command to output
                 # sensible output so we can parse it
  shell: "munin-run --servicedir /usr/share/munin/plugins {{ munin_plugin }} suggest 2>/dev/null || true"
  changed_when: false

#- name: debug
#  debug:
#    var: suggests
#
- name: implement munin {{ munin_plugin }} suggests
  include_tasks: roles/monitoring/tasks/munin_suggest_plugin_item.yml
  loop_control:
    loop_var: suggest_item
  with_items: "{{ suggests.stdout_lines }}"
    
