---
- name: restart dnsmasq
  # actually, remove reservations first (but we have to keep this name
  # because other callers call us on it.  Ideally these would just be
  # a block)
  file:
    dest: /tmp/dhcp.leases
    state: absent
  notify: restart dnsmasq service

- name: restart dnsmasq service
  service:
    name: dnsmasq
    state: "{{ 'restarted' if inventory_hostname != 'gateway-tmp' else 'stopped' }}"
  throttle: 1
  notify: reload wifi  # might as well actually reload wifi interfaces
                       # to force devices to fetch their DHCP updated
                       # addresses

- name: restart firewall
  service:
    name: firewall
    state: restarted

- name: uci commit
#  debug:
#    msg: "not running uci commit!"
  uci:
    command: commit
  notify: reload wifi

- name: reload wifi
  service:
    name: network    # go full network partially because there's no
                     # "wifi service" per se, but network does restart
                     # wifi, but also make sure we pick up any new
                     # VLAN configurations...
    state: restarted
  throttle: 1

- name: restart usteer
  service:
    name: usteer
    state: restarted

- name: restart lldpd
  service:
    name: lldpd
    state: restarted
