---
- name: "install conf files for user {{ user }}"
  include_tasks: install_user_dir_file_or_template.yml
  loop_control:
    loop_var: file_or_template
  with_items: "{{ install_user_files.files }}"

