---
# copies a file to .name, from .source, defaulting to homes/<name> if
# .source isn't provided

- name: "install user file: ~{{ user }}/{{ file_or_template.name }} from {{ source }}"
  copy:
    dest: "~{{ user }}/{{ file_or_template.name }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    src: "{{ source }}"
    mode: "{{ file_or_template.mode | default(omit) }}"
  become: true
  become_user: "{{ user }}"
