---
# allow the caller to supply {{ lines }} to ensure exist in the output
# file, or a {{ source }} file or a {{ source.j2 }} template

- name: find source name
  # might actually not be asked for - especially in the case of lines
  # in file, but no harm calculating here to simplify later

  # We prepend "homes/" by default.  We could remove "./" with "|
  # regex_replace('/\\./', '/')", but it complicates things too much
  # later
  set_fact:
    source: "{{ dir_file_or_template.source | default ( 'homes/' ~ dir_file_or_template.name ) }}"

- include_tasks: install_user_file_lines.yml
  when: dir_file_or_template.lines is defined

- include_tasks: install_user_directory.yml
  when: ( source is regex(".*/$") ) and
        ( not ( dir_file_or_template.remove | default(false) ) )

- include_tasks: remove_user_directory.yml
  when: ( source is regex(".*/$") ) and
        ( dir_file_or_template.remove | default(false) )

- include_tasks: install_user_file.yml
  when: ( source is not regex(".*\\.j2$") ) and
        ( source is not regex(".*/$") )
# unlike install_dir_file_or_template, we resolve the symlink locally
# in all cases, because half the time they refer back to something on
# the filesystem of my ansible server

- include_tasks: install_user_template.yml
  when: ( source is regex(".*\\.j2$") )
        # implied can't also be directory

