---
# allow the caller to supply {{ lines }} to ensure exist in the output
# file, or a {{ source }} file or a {{ source.j2 }} template

- name: find source name
  # might actually not be asked for - especially in the case of lines
  # in file, but no harm calculating here to simplify later

  # We prepend "homes/" by default.  We could remove "./" with "|
  # regex_replace('/\\./', '/')", but it complicates things too much
  # later
  set_fact:
    source: "{{ file_or_template.source | default ( 'homes/' ~ file_or_template.name ) }}"

# ensure the destination directory exists so we can add a line to it
# if necessary, but don't go converting any symlinks to dirs
- name: "Does   {{ ( '~' ~ user ~ '/' ~ file_or_template.name ) | dirname }} exist?"
  stat:
    path:      "{{ ( '~' ~ user ~ '/' ~ file_or_template.name ) | dirname }}"
  become: true
  register: dirtest

- name: "Create {{ ( '~' ~ user ~ '/' ~ file_or_template.name ) | dirname }}/"
  file:
    path:      "{{ ( '~' ~ user ~ '/' ~ file_or_template.name ) | dirname }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  become: true
  when: not dirtest.stat.exists

- include_tasks: install_user_file_lines.yml
  when: file_or_template.lines is defined

- include_tasks: install_user_directory.yml
  when: ( source is regex(".*/$") ) and
        ( not ( file_or_template.remove | default(false) ) )

- include_tasks: remove_user_directory.yml
  when: ( source is regex(".*/$") ) and
        ( file_or_template.remove | default(false) )

- include_tasks: install_user_file.yml
  when: ( source is not regex(".*.j2$") ) and
        ( source is not regex(".*/$") )

- include_tasks: install_user_template.yml
  when: ( source is regex(".*.j2$") )
        # implied can't also be directory

