---
# copies a directory to .name, from .source, defaulting to homes/<name> if
# .source isn't provided

- include_tasks: calculate_directory_contents.yml

- name: "install user file under directory: ~{{ user }}/{{ file_or_template.name }}"
  copy:
    dest: "~{{ user }}/{{ file_or_template.name }}{{ file_recurse.path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    src: "{{ file_recurse.src }}"
    mode: "{{ file_or_template.mode | default(file_recurse.mode) }}"
    follow: true # allow a user to symlink their files directly into
                 # this git repo if they happen to be treating their
                 # editing desktop environment as ansible master, and
                 # always have the latest copy of their config.  We do
                 # have to be careful not to allow symlink attacks, so
                 # become the user first
  become: true
  become_user: "{{ user }}"
  loop_control:
    loop_var: file_recurse
    label: "~{{ user }}/{{ file_or_template.name }}{{ file_recurse.path }}"
  with_items: "{{ file_list }}"
  when: ( file_recurse.state == 'file' )

- name: "install user file symlink under directory: ~{{ user }}/{{ file_or_template.name }}"
  file:
    dest: "~{{ user }}/{{ file_or_template.name }}{{ file_recurse.path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    src: "{{ file_recurse.src }}"
  become: true
  become_user: "{{ user }}"
  loop_control:
    loop_var: file_recurse
    label: "~{{ user }}/{{ file_or_template.name }}{{ file_recurse.path }}"
  with_items: "{{ file_list }}"
  when: ( file_recurse.state == 'link' )
