---
# generates a file .name, from template .source.j2

- name: "install user file per template: ~{{ user }}/{{ file_or_template.name }} "
  template:
    dest: "~{{ user }}/{{ file_or_template.name }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    src: "{{ source }}"
    mode: "{{ file_or_template.mode | default(omit) }}"
  become: true
  become_user: "{{ user }}"
