#!/bin/bash

trap fail ERR

fail=false

failed_tests=

function fail() {
    code=$? ; CMD="$BASH_COMMAND"
    echo " * -> Failed($code): $CMD"

    failed_tests="$failed_tests$CMD ; "
    fail=true
}

cd /usr/local/bin/nagios

fss=$( ceph fs ls | sed 's/,//' | awk '{print $2}' )
pools=$( ceph osd pool ls )
hostname=$( hostname )

for pool in $pools ; do
    ./check_ceph_df -W 90 -C 95 -p $pool
done
./check_ceph_health
# a and b, but they're all on a standby arrangement and some aren't
# up.  I'm not actually quite sure of what defines healthy, so let's
# keep trying!
for mds in `hostname`-a `hostname`-b ; do # each worker needs to be
                                          # responsible for something?
    success=false
    for fs in $fss ; do
        if ./check_ceph_mds -n $mds -f $fs ; then
            success=true
        fi
    done
    if ! $success ; then
        echo $mds failed on one of: ./check_ceph_mds -n $mds -f: $fss
        fail=true
    fi
done
./check_ceph_mgr
./check_ceph_mon -I $hostname
./check_ceph_osd -H $hostname
./check_ceph_osd_df -W 90 -C 95
#./check_ceph_rgw  # rados gateway to S3

if $fail ; then
    echo Failed tests: $failed_tests
    exit 1
fi
