---
- name: Allow ssh traffic on custom port
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
  become: true

- name: Allow http traffic on port 80
  ufw:
    rule: allow
    port: 80
    proto: tcp
  become: true

- name: Allow https traffic on port 443
  ufw:
    rule: allow
    port: 443
    proto: tcp
  become: true

# FIXME: parameterise all firewall ports - this one is needed for pve, so fix this at a later date
- name: Allow https traffic on port 8006
  ufw:
    rule: allow
    port: 8006
    proto: tcp
  become: true

- name: Enable firewall
  ufw:
    state: enabled
    policy: deny
  become: true
