function setup_display() {
    if [ -n "$DISPLAY" ] ; then
        # stop trying to store masses of keys in NFS $HOME - just start
        # off with the current DISPLAY's key and put it into a new file in
        # /tmp
        if [ -z "$XAUTHORITY" ] ; then
            export XAUTHORITY=$HOME/.Xauthority
        fi
        if [ "$XAUTHORITY" != "/tmp/.$USER.$DISPLAY" ] ; then
            # RHEL5 is doesn't parse $DISPLAY correctly when the local
            # hostname is in it.  Ignore rhel5 and fall back to default behaviour
            #FIXME: times out
            auth=$( timeout -k 1 1 xauth nextract - $DISPLAY 2>/dev/null )
            XAUTHORITY=/tmp/.$USER.$DISPLAY ; export XAUTHORITY
            touch $XAUTHORITY
            if [ -n "$auth" ] ; then
                echo "$auth" | timeout -k 1 1 xauth nmerge -
            fi
        fi

        #if using root, etc, let it use the display (only tested on Lunix)
        #    PUSER=`ps --noheader u $PPID 2>/dev/null | awk '{print $1}'`  #let the parent set this
        if [ "$PUSER" != root -a "$PUSER" != "" -a "$PUSER" != "$USER" ] ; then
            #  /tmp/.$PUSER.Xauthority.tmp is generated by sillysu()
            # export XAUTHORITY=`eval echo ~"$USER"/.Xauthority`
            #FIXME: times out
            ( cat /tmp/.$PUSER.Xauthority.tmp | timeout -k 1 1 xauth merge - ) >& /dev/null
        fi
    fi

    if [ -n "$DISPLAY" ] && programexists xrandr ; then  # -a -z "$NONINTERACT"
        dpyinfo=`xrandr --current | grep ' connected \(primary \)\?[0-9]'`
        size1info=`echo "$dpyinfo" | sed 's/.* \([0-9]*x[0-9]*\)+\([0-9]*\).*/\2 \1/' | sort -g | tail -n +1 | head -n 1 | awk '{print $2}'`
        size2info=`echo "$dpyinfo" | sed 's/.* \([0-9]*x[0-9]*\)+\([0-9]*\).*/\2 \1/' | sort -g | tail -n +2 | head -n 1 | awk '{print $2}'`
        size3info=`echo "$dpyinfo" | sed 's/.* \([0-9]*x[0-9]*\)+\([0-9]*\).*/\2 \1/' | sort -g | tail -n +3 | head -n 1 | awk '{print $2}'`
        if [ -z "$size2info" ] ; then
            size2info="$size3info"
            size3info=
        fi
        if [ -z "$size1info" ] ; then
            size1info="$size2info"
            size2info="$size3info"
            size3info=
        fi
        if [ -n "$size3info" ] ; then
            export  HORSIZE=`echo "$size2info" | sed -n 's!\([^x]*\)x\([^x]*\)!\1!p'`
            export VERTSIZE=`echo "$size2info" | sed -n 's!\([^x]*\)x\([^x]*\)!\2!p'`
            export  HOR2SIZE=`echo "$size3info" | sed -n 's!\([^x]*\)x\([^x]*\)!\1!p'`
            export VERT2SIZE=`echo "$size3info" | sed -n 's!\([^x]*\)x\([^x]*\)!\2!p'`
            export  HOR0SIZE=`echo "$size1info" | sed -n 's!\([^x]*\)x\([^x]*\)!\1!p'`
            export VERT0SIZE=`echo "$size1info" | sed -n 's!\([^x]*\)x\([^x]*\)!\2!p'`
        elif [ -n "$size2info" ] ; then
            export  HORSIZE=`echo "$size1info" | sed -n 's!\([^x]*\)x\([^x]*\)!\1!p'`
            export VERTSIZE=`echo "$size1info" | sed -n 's!\([^x]*\)x\([^x]*\)!\2!p'`
            export  HOR2SIZE=`echo "$size2info" | sed -n 's!\([^x]*\)x\([^x]*\)!\1!p'`
            export VERT2SIZE=`echo "$size2info" | sed -n 's!\([^x]*\)x\([^x]*\)!\2!p'`
        else
            export  HORSIZE=`echo "$size1info" | sed -n 's!\([^x]*\)x\([^x]*\)!\1!p'`
            export VERTSIZE=`echo "$size1info" | sed -n 's!\([^x]*\)x\([^x]*\)!\2!p'`
        fi
        export MULTIPLE_MONITORS=$(echo "$dpyinfo" | wc -l)
        if [ "$MULTIPLE_MONITORS" = 1 ] ; then
            unset MULTIPLE_MONITORS
        fi
        
        SHORTCANONICALDISP=`echo "$DISPLAY" | sed "s/^:/$SHORTHOST:/"`
        CANONICALDISP=`     echo "$DISPLAY" | sed "s/^:/$HOST:/"`
        SHORTDISPHOST=`echo "$DISPLAY" | sed 's/:.*//' | sed 's/\..*$//'`
        if [ -z "$SHORTDISPHOST" ] ; then
            SHORTDISPHOST=$SHORTHOST
        fi
        export SHORTCANONICALDISP CANONICALDISP SHORTDISPHOST
    fi
}
