#!/bin/bash
#
# munin plugin to monitor difference between system time and a random
# upstream ntp server, to pick up those cases where local ntp server
# has dropped all its upstreams, so can no longer query status of a
# fixed server within that pool
#
# Origional Author: Tim Connors
# Contributors: none
# Version: 1.2 Adaption to chronyc
# Version: 1.1 single-shot ntpdate against a chosen target
#
#%# family=contrib
#%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

set -e

offset_line=$( timeout 10 chronyc -c sources | sed 's/,/ /g' | grep '^^ \* ' )
read a b ip stratum e f last current_offset measured_offset err <<< "$offset_line"

server=$( dig -x "$ip" +short | sed 's/\.$//' )

case $1 in
    autoconf)
	echo yes
	exit 0
	;;
    config)
        echo 'graph_title NTP real offset'
        #        echo 'graph_args --base 1000 -l 0 '
#        echo 'graph_scale no'
        echo 'graph_vlabel offset (seconds)'
        echo 'graph_category time'

        echo "offset.label $server"

        echo

        exit 0
	;;
esac

[ -n "$current_offset" ] && echo offset.value $current_offset
