
(defun sweyla902670 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/902670/"
  (interactive)
  (color-theme-install
   '(sweyla902670
     ((background-color . "#020704")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#A44A0C"))))
     (font-lock-constant-face ((t (:foreground "#00FF63"))))
     (font-lock-builtin-face ((t (:foreground "#C71A3F"))))
     (font-lock-function-name-face ((t (:foreground "#00837F"))))
     (font-lock-variable-name-face ((t (:foreground "#92D35C"))))
     (font-lock-keyword-face ((t (:foreground "#3F4F60"))))
     (font-lock-string-face ((t (:foreground "#00609E"))))
     (font-lock-doc-string-face ((t (:foreground "#00609E"))))
     (font-lock-type-face ((t (:foreground "#206788"))))
     )))

(provide 'sweyla902670)
