---
# If you want these handlers to run as root, the playbook has to be
# running as root, or you have to include the role as root

- name: "Update initramfs config"
  shell: "/usr/sbin/update-initramfs -u -k all"

- name: "Regenerate boot config"
  include_tasks: "{{ playbook_dir }}/roles/common_handlers/handlers/regenerate_boot_config.yml"

- name: restart cron
  service:
    name: cron
    state: restarted

- name: restart munin-node
  service:
    name: munin-node
    state: restarted
  ignore_errors: true # might not be installed yet

- name: restart nut server
  service:
    name: nut-server
    state: restarted

- name: restart nut monitor
  service:
    name: nut-monitor
    state: restarted

- name: restart autofs
  service:
    name: autofs
    state: restarted

- name: restart autofs
  service:
    name: autofs
    state: restarted

- name: "systemd daemon reload"
  systemd:
    daemon_reload: true

- name: restart systemd-logind
  service:
    name: systemd-logind
    state: restarted

- name: restart ssh
  service:
    name: ssh
    state: restarted
  become: true

- name: restart apache2
  service:
    name: apache2
    state: restarted
  become: true
  when: "'apache2' in ansible_facts.packages | default([])"

- name: restart chrony
  service:
    name: chrony
    state: restarted
  become: true
  ignore_errors: true # very first step in playbook is to install
                      # files and run those handlers - chrony might
                      # not be installed yet though
  when: host_is_container is not defined
