---
- name: Install fileserver packages
  apt:
    name: ['zfs-dkms', 'samba']
    update_cache: yes
    cache_valid_time: 0
    autoremove: no
    state: present
  become: true

- name: ensure files publicly readable (mainly for public_html)
  ini_file:
    path: /etc/samba/smb.conf
    section: users
    option: create mask
    value: '0755'
  notify: restart smbd
  become: true

- name: ensure directories publicly readable (mainly for public_html)
  ini_file:
    path: /etc/samba/smb.conf
    section: users
    option: directory mask
    value: '0755'
  notify: restart smbd
  become: true

- name: set our ZFS fileserver options
  lineinfile:
    dest: /etc/default/zfs
    backrefs: yes
    # using a negative lookahead, match everything that's eg:
    # ^CRON_DAILY_RUN, so long as it's not already
    # '^CRON_DAILY_RUN="true"':
    regexp: "^({{ item.key }}=(?!'{{ item.value }}').*)"
    line: "#\\1\\n{{ item.key }}='{{ item.value }}'"
  become: true
  with_items:
    "{{ lookup('ansible.builtin.dict', default_zfs_flags) }}"

- name: Make sure all handlers run
  meta: flush_handlers
