---
# generates list of files in a .source directory

- name: unconditionally (highest precedence) initialise file_list
  set_fact:
    file_list:
      directory: []
      file: []
      link: []

- name: "construct list of files being {{ 'deleted' if ( dir_file_or_template.delete | default(false) ) else 'installed' }} in {{ dir_file_or_template.name }} from {{ source }}"
  set_fact:
    # https://stackoverflow.com/questions/38143647/set-fact-with-dynamic-key-name-in-ansible
    file_list: "{{ file_list | combine({file_recurse.state: [file_recurse]}, recursive=true, list_merge='append') }}"
#  vars:
#    file_list: []   # higher precedence than set_fact, and initialises correctly, but doesn't reinitialise each loop?
  loop_control:
    loop_var: file_recurse
    label: "[{{file_recurse.state}}]={{ user | default('') }}/{{ dir_file_or_template.name }}{{ file_recurse.path }}"
  with_community.general.filetree: "{{ source }}"
  run_once: true
  # filter in only files and links, and out all files in .git, CVS etc
  when: (
          ( file_recurse.state == 'file' ) or
          ( file_recurse.state == 'link' ) or
          ( file_recurse.state == 'directory' )
        ) and
        (
          ( file_recurse.path is not regex('(^|/).*~$' ) ) and
          ( file_recurse.path is not regex('(^|/).git(/|$)' ) ) and
          ( file_recurse.path is not regex('(^|/)CVS(/|$)' ) ) and
          ( file_recurse.path is not regex('(^|/)readme.txt(/|$)' ) )
        )

# FIXME: it'd be nice to act on .j2 files as well, but if we try to
# template them, the template will search templates/ rather than under
# files/ where we intend to find them with file_recurse
# https://serverfault.com/questions/578544/deploying-a-folder-of-template-files-using-ansible
