---
- name: "fixup conf file {{ file.name }} for user {{ user }}"
  lineinfile:
    dest: "~{{ user }}/{{ file.name }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    line: "{{ item }}"
    mode: "{{ file.mode | default(omit) }}"
    create: yes
  become: true
  with_items: "{{ file.lines }}"

#- name: "ensure permissions are correct on {{ file.name }} for user {{ user }}"
#  when: file.mode is defined  # stop spurious messages about "changed" when the file is a symlink to common-files/
#  file:
#    dest: "~{{ user }}/{{ file.name }}"
#  become: true
