---
- name: Install tools required by physical hardware
  apt:
    name: ['lm-sensors', 'gparted', 'xauth', 'powertop', 'sg3-utils', 'scsitools', 'bonnie++', 'apt-file', 'rasdaemon', 'linux-cpupower', 'nvme-cli', 'numactl', 'numad', 'numatop'] # rasdaemon has taken over from mcelog which is no longer available
    update_cache: yes
    cache_valid_time: 3600
    autoremove: no
    state: present
  become: true

- name: Install tools wanted by intel hardware
  apt:
    name: ['i7z', 'thermald'] # i8kutils for delll machines? thermald auto-disables itself if hardware doesn't have required capabilities
    update_cache: yes
    cache_valid_time: 3600
    autoremove: no
    state: present
  become: true
  when: host_is_intel | default(false)

- name: "Ensure sensors in /etc/modules-load.d/sensors.conf for hddtemps to be reported through `sensors`"
# FIXME: modprobe drivetemp, coretemp, run sensors-detect, insert those modules into /etc/modprobe, and rerun munin-node:
#  echo drivetemp > /etc/modules-load.d/drivetemp.conf
  copy:
    dest: /etc/modules-load.d/sensors.conf
    content: |2
      # ansible controlled for sensors by physical/tasks/main.yml
      coretemp
      drivetemp
  become: true
  notify: "Update initramfs config"
