---
- name: install apache and letsencrypt certbot
  apt:
    name: [ 'apache2', 'javascript-common', 'python3-certbot-apache' ]

- name: localalize error pages
  lineinfile:
    dest: /etc/apache2/conf-enabled/localized-error-pages.conf
    insertafter: '^#ErrorDocument 404'
    line: 'ErrorDocument 404 /404.html'
  become: true
  notify: restart apache2

- name: install apache proxy and rewrite confs
  copy:
    src: etc/apache2/{{ item }}
    dest: /etc/apache2/
  become: true
  notify: restart apache2
  with_items:
    - rather.puzzling.org-rewrite.conf
    - rather.puzzling.org-proxy.conf

- name: remove default apache 000-default.conf
  file:
    dest: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  become: true
  notify: restart apache2

- name: install our apache sites
  copy:
    src: etc/apache2/sites-enabled/
    dest: /etc/apache2/sites-enabled/
  become: true
  notify: restart apache2

- name: install our apache sites
  copy:
    src: etc/apache2/secrets/
    dest: /etc/apache2/secrets/
    owner: www-data
    group: www-data
    mode: 0640
  become: true
#  notify: restart apache2

- name: enable apache modules
  apache2_module:
    name: "{{ item.name | default( item ) }}"
    state: "{{ item.state | default('present') }}"
  loop:
    - expires
    - headers
    - include
    - proxy
    - proxy_http
    - proxy_wstunnel
    - rewrite
    - ssl
    - userdir
  become: true
  notify: restart apache2
#FIXME: original mods-enabled:
#cgi - later, if necessary
#fcgid - later, if necessary
#mpm_prefork instead of mpm_event, later, if necessary
#perl, php, python if necessary, or will everything that needs that be redirected?
# php*.ini if necessary (upload_tmp_dir = /tmp; sqlite3.defensive = 1 was turned off at one stage
# php*.conf may need public_html section commented out
# /etc/cron.d/php?

- name: Fix permissions on /var/log/apache2
  file:
    dest: /var/log/apache2
    mode: 0755
  become: true

- name: Setup monitoring against known letsencrypt failures and non-renewal of cert
  copy:
    src: etc/cron.daily/check_letsencrypt_certbot
    dest: /etc/cron.daily/check_letsencrypt_certbot
    mode: 0755
  become: true

- name: comment out existing userdir entries
  lineinfile:
    regexp: "^\t{{ item }}"
    line: "\t#{{ item }}"
    path: /etc/apache2/mods-available/userdir.conf
  with_items:
    - AllowOverride FileInfo AuthConfig Limit Indexes
    - Options MultiViews Indexes SymLinksIfOwnerMatch IncludesNoExec
  become: true
  notify: restart apache2

- name: ensure our userdir options
  lineinfile:
    insertafter: "{{ item.search }}"
    line: "\t{{ item.replace }}"
    #FIXME: we'd need a regexp here if we wanted to ever change the
    #options below, but then that will clash with insertafter:
    path: /etc/apache2/mods-enabled/userdir.conf
  with_items:
    - { search: AllowOverride, replace: AllowOverride All }
    - { search: Options, replace: Options Indexes FollowSymLinks ExecCGI }
  become: true
  notify: restart apache2
  # FIXME: if we want to reinstate cgi-bin, we want:
  #        <Directory /home/*/public_html/cgi-bin>
  #              AllowOverride FileInfo AuthConfig Limit Indexes
  #              Options ExecCgi MultiViews Indexes SymLinksIfOwnerMatch IncludesNoExec
  #              XBitHack on
  #              AddHandler cgi-script .cgi
  #        </Directory>


#FIXME: we would rather let ansible do the letsencrypt bootstrapping
#(since we're starting off setting apache to redirect all http->https
#via a snakeoil cert, this makes it hard for us to bootstrap using
#letsencypt using the official methods), but for now let's just seed
#it with a copy from the original webserver, and store the letsencrypt
#configuration directory in our proxmox host's non-volatile storage
#FIXME: original letsencrypt contents saved in webserver:/etc/letsencrypt.orig/

# caution (just remove them from the filesystem, install the scripts (which obviously can't be called from this non-cgi enabled machine anyway) since scripts should already be calling the correct master):
#   ./.whether_in_bed
#   ./.whether_phone_screen_on
#   ./.whether_study_uninhabited
#   ./.offdayshift
#   temp-ac.ajaxy.js
#   temp-ac.feedback.js


