---
- name: enable apache modules
  apache2_module:
    name: "{{ item.name | default( item ) }}"
    state: "{{ item.state | default('present') }}"
  loop:
    - expires
    - headers
    - include
    - userdir
    - cgid
  become: true
  notify: restart apache2

- name: Fix permissions on /var/log/apache2
  file:
    dest: /var/log/apache2
    mode: 0755
  become: true

- name: include external website tasks
  include_tasks: external_website.yml
  when: host_is_ext_web_server | default(false)





