---
- name: "Search for spectre/meltdown unmitigation {{ mitigation_flag }} in grub config"
  become: yes
  register: grub_variable_line_exists
  check_mode: yes # cause this to become just a test.  If there's already
                  # spectre settings, then this will think line is
                  # being replaced, and changed will become true (but we
                  # force it to false to not output a line saying
                  # "changed"), and msg will become "line added", else
                  # changed stays false, and msg does not contain "line
                  # added"
                  #
                  # We need to use this strange form because backrefs
                  # is used by next test, and modifies lineinfile to
                  # not try to add the line
  lineinfile:
    dest: /etc/default/grub
    line: grub cmdline already has spectre mitigation disabled
    regexp: "^{{ variable }}=.*{{ mitigation_flag }}"
    state: present
  changed_when: false

- name: "Append spectre unmitigation {{ mitigation_flag }} grub config"
  when: grub_variable_line_exists.msg == "line added"
  lineinfile:
    dest: /etc/default/grub
    backrefs: yes
    regexp: "^{{ variable }}=\"(.*)\""
    line: "{{ variable }}=\"\\1 {{ mitigation_flag }}\""
    state: present
  become: true
  notify: "Regenerate grub config"
