---
- name: "Append spectre unmitigations grub config"
  include_tasks: add_grub_flag.yml
  loop_control:
    loop_var: mitigation_flag
  when: host_needs_no_spectre_mitigations is not defined
  with_items: { nopti, nospectre_v2, nospectre_v1, noibrs, noibpb, l1tf=off, nospec_store_bypass_disable, no_stf_barrier, mds=off, mitigations=off }

- name: "Remove spectre unmitigations grub config"
  when: host_needs_no_spectre_mitigations is defined
  lineinfile:
    dest: /etc/default/grub
    backrefs: yes
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT=\"(.*) *{{ item }} *(.*)\""
    line: "GRUB_CMDLINE_LINUX_DEFAULT=\"\\1\\2\""
    state: present
  become: true
  with_items: { nopti, nospectre_v2, nospectre_v1, noibrs, noibpb, l1tf=off, nospec_store_bypass_disable, no_stf_barrier, mds=off, mitigations=off, "   *" }
  notify: "Regenerate grub config"

