---
- name: remove conflicting and/or obsolete packages
  opkg:
    name: luci-app-dawn,dawn
    state: absent

- name: install compulsory packages
  opkg:
    name: bash,muninlite,rsync
    state: present

- name: install router packages
  opkg:
    # kmod-tcp-bbr was on b1300 prior to 21.02.1 upgrade - no idea how
    # it got there
    name: luci-app-sqm,avahi-dbus-daemon,adblock,luci-app-adblock,msmtp,crelay,ethtool,arp-scan,ifstat # luci-app-banip has disappeared from b1300, but we want to be able to reinstall it if it becomes available again
    state: present
  when: openwrt_router_packages is defined

- name: install AP packages
  opkg:
    name: usteer
    state: present
  when: openwrt_router_packages is not defined

- name: install full packages
  opkg:
    name: tcpdump,strace
    state: present
  when: openwrt_heavy_installation is defined

- name: setup dhcp reservations
  copy:
    dest: /etc/config/dhcp
    content: "{{ lookup('file', 'roles/openwrt/files/dhcp.head.{{ type }}')}}\n\n{{lookup('file', 'roles/openwrt/files/dhcp.reservations') }}\n"
  notify: restart dnsmasq

