---
- name: Update DHCP config
  include_tasks: update_dhcp.yml
  when: (update_dhcp | default(true) | bool) or (fast_update_dhcp | default(false) | bool)

- name: include package config
  include_tasks: packages_config.yml
  when: run_packages_config | default(true) | bool

- name: include uci config
  include_tasks: uci_config.yml
  when: run_uci_config | default(false) | bool

- name: commit changes
  meta: flush_handlers
