---
- name: "fixup conf file {{ file.name }} for user {{ user }}"
  lineinfile:
    dest: "~{{ user }}/{{ file.name }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    line: "{{ item }}"
    create: yes
  become: true
  with_items: "{{ file.lines }}"
    

